name: Sync Github Repos To Gitee

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Sync Github Repos To Gitee  # 名字随便起
      uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
      with:
        src: github/git@github.com:WTxiaomage/react-blog.git  # 源端账户名(github)
        dst: gitee/git@gitee.com:WTxiaomage_admin/react-blog.git  # 目的端账户名(gitee)
        dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
        account_type: org  # 账户类型
